name: void
channels:
  - conda-forge
  - nodefaults
dependencies:
  - r-base >= 4.3.0
  - r-shiny
  - r-bslib
  - r-tidyverse
  - r-rlang
  - r-dt
  - r-shinyace
  - r-shinyjqui
  - r-bsicons
  - r-testthat
  - r-roxygen2
  - r-usethis
  - r-devtools
